// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB88UnRb5bTimowBpaeUpqFc2pQs8_ilA8',
    appId: '1:758299826793:web:b18210baf905e88ec7a0f8',
    messagingSenderId: '758299826793',
    projectId: 'we-chat-2c0c7',
    authDomain: 'we-chat-2c0c7.firebaseapp.com',
    storageBucket: 'we-chat-2c0c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuOxNTu-QrkHhtvoyRnhrH0ixLGOSqM-4',
    appId: '1:758299826793:android:6ff534f3ab6e5b1ec7a0f8',
    messagingSenderId: '758299826793',
    projectId: 'we-chat-2c0c7',
    storageBucket: 'we-chat-2c0c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ZJv9p5VUxIYuq56FzK0-7_uVQu4tN1Y',
    appId: '1:758299826793:ios:33d32231b4f5ac1dc7a0f8',
    messagingSenderId: '758299826793',
    projectId: 'we-chat-2c0c7',
    storageBucket: 'we-chat-2c0c7.appspot.com',
    androidClientId: '758299826793-jte1bkcdgdhi5ll5eillqafgfrgiiflr.apps.googleusercontent.com',
    iosClientId: '758299826793-jeaco4f8a1e4intpt7qrrk51vck7qt37.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_ZJv9p5VUxIYuq56FzK0-7_uVQu4tN1Y',
    appId: '1:758299826793:ios:33d32231b4f5ac1dc7a0f8',
    messagingSenderId: '758299826793',
    projectId: 'we-chat-2c0c7',
    storageBucket: 'we-chat-2c0c7.appspot.com',
    androidClientId: '758299826793-jte1bkcdgdhi5ll5eillqafgfrgiiflr.apps.googleusercontent.com',
    iosClientId: '758299826793-jeaco4f8a1e4intpt7qrrk51vck7qt37.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB88UnRb5bTimowBpaeUpqFc2pQs8_ilA8',
    appId: '1:758299826793:web:7ef39a1b22b8b3a0c7a0f8',
    messagingSenderId: '758299826793',
    projectId: 'we-chat-2c0c7',
    authDomain: 'we-chat-2c0c7.firebaseapp.com',
    storageBucket: 'we-chat-2c0c7.appspot.com',
  );

}